// auto-generated by circomkit
pragma circom 2.1.6;

include "../market/ethAddrMarket.circom";

component main {public[encryptedPrivateECDSAKey, sharedKeyHash, poseidonNonce]} = SellETHAddress(64, 4);
